services:
  frontend:
    image: node:alpine3.19
    working_dir: /app
    entrypoint: ["npm"]
    command: ["run", "dev"]
    restart: unless-stopped
    volumes:
      - ../frontend:/app:755
    environment:
      WATCHPACK_POLLING: true # Enables HMR for Windows

  backend:
    image: node:alpine3.19
    working_dir: /app
    entrypoint: ["npm"]
    command: ["run", "dev"]
    restart: unless-stopped
    volumes:
      - ../backend:/app:755
    ports:
      - 8080:3000
    environment:
      WATCHPACK_POLLING: true # Enables HMR for Windows

  database:
    ports:
      - 3306:3306
