version: "3"
name: bs3206

services:
  frontend:
    depends_on: 
      - backend
    hostname: frontend
    container_name: frontend
    image: bs3206-img-frontend:latest
    build: 
      context: ../frontend
      dockerfile: ../docker/frontend.dockerfile
    ports:
      - 80:3000
    networks:
      - frontend 
      - dmz

  backend:
    depends_on: 
      - database
    hostname: backend
    container_name: backend
    image: bs3206-img-backend:latest
    build:
      context: ../backend
      dockerfile: ../docker/backend.dockerfile
    expose: 
      - 3000
    networks:
      - backend 
      - dmz

  database:
    hostname: database
    container_name: database
    image: mysql:8.3.0-oraclelinux8
    expose:
      - 3306
    networks:
      - backend
    volumes:
      - ../database/build-scripts:/docker-entrypoint-initdb.d:555
    environment:
      MYSQL_ROOT_PASSWORD: pass 
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

networks:
  frontend:
    driver: bridge
  dmz:
    driver: bridge
  backend:
    driver: bridge
