-- MySQL Script generated by MySQL Workbench
-- Thu 18 Apr 2024 11:56:37 BST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ims
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ims
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ims` ;
USE `ims` ;

-- -----------------------------------------------------
-- Table `ims`.`vehicle_specifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ims`.`vehicle_specifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(255) NOT NULL,
  `model` VARCHAR(255) NOT NULL,
  `image` BLOB NULL,
  `emissions` DECIMAL(4,2) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `brand_model_UNIQUE` (`brand` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ims`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ims`.`vehicles` (
  `license_plate` VARCHAR(8) NOT NULL,
  `specifications_id` INT NULL,
  PRIMARY KEY (`license_plate`),
  UNIQUE INDEX `license_plate_UNIQUE` (`license_plate` ASC) VISIBLE,
  INDEX `fk_vehicles_1_idx` (`specifications_id` ASC) VISIBLE,
  CONSTRAINT `fk_specifications_id`
    FOREIGN KEY (`specifications_id`)
    REFERENCES `ims`.`vehicle_specifications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
